### ISSUE TITLE
thank you for the script

### ISSUE THREAD

**Issue by dj-nitehawk** [ravindusha/SLT_Usage_Meter_Addon#1]
hi...

just wanted to say thank you very much for creating this script. it's extremely helpful.

i also made a couple of customizations to suit my needs as [shown here](https://github.com/dj-nitehawk/SLT_Usage_Meter_Addon/commit/b5e2b487fffbb836e23f21fd91a49a26bba63113)

thanks again and have a nice day!

cheers!

**Comment by ravindusha** [comment]
You are welcome. Adding the data buffer was a nice idea.
